import { Category, HeroSlide, Product, SiteSettings, Testimonial } from '../types';

export const defaultCategories: Category[] = [
  {
    _id: 'cat-accessories',
    name: 'الإكسسوارات',
    slug: { current: 'accessories' },
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
    description: 'قلائد مطلية بالذهب، أساور راقية، وأقراط أنيقة صممت لتبرز جاذبيتك الفاتنة.',
    order: 1,
    active: true,
    itemCount: 14,
  },
  {
    _id: 'cat-makeup',
    name: 'المكياج',
    slug: { current: 'makeup' },
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'أحمر شفاه حريري، باليتات ظلال ساحرة، ومستحضرات تجميل أصلية 100%.',
    order: 2,
    active: true,
    itemCount: 18,
  },
  {
    _id: 'cat-skincare',
    name: 'منتجات العناية',
    slug: { current: 'skincare' },
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    description: 'سيرومات نضارة، مرطبات مكثفة، وزيوت طبيعية لنقاء وإشراقة تدوم.',
    order: 3,
    active: true,
    itemCount: 12,
  },
  {
    _id: 'cat-beauty-tools',
    name: 'أدوات التجميل',
    slug: { current: 'beauty-tools' },
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=800&auto=format&fit=crop',
    description: 'فراشي مخملية احترافية، رول تدليك الكوارتز، وأدوات تطبيق دقيقة.',
    order: 4,
    active: true,
    itemCount: 9,
  },
  {
    _id: 'cat-hair-accessories',
    name: 'إكسسوارات الشعر',
    slug: { current: 'hair-accessories' },
    image: 'https://images.unsplash.com/photo-1535295972055-1c762f4483e5?q=80&w=800&auto=format&fit=crop',
    description: 'مشابك لؤلؤية فاخرة، أطواق حريرية مرصعة، وتيجان ناعمة لأبهى إطلالة.',
    order: 5,
    active: true,
    itemCount: 11,
  },
  {
    _id: 'cat-bags',
    name: 'الحقائب',
    slug: { current: 'bags' },
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    description: 'حقائب يد جلدية كلاسيكية وكلاتشات سهرة راقية بتفاصيل ذهبية مذهلة.',
    order: 6,
    active: true,
    itemCount: 8,
  },
  {
    _id: 'cat-beauty-care',
    name: 'منتجات الجمال',
    slug: { current: 'beauty-products' },
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    description: 'عطور راقية وبخاخات مسك وجسم لإحساس دائم بالانتعاش والتميز.',
    order: 7,
    active: true,
    itemCount: 15,
  },
];

export const defaultProducts: Product[] = [
  {
    _id: 'prod-1',
    name: 'عقد ذهبي مرصع بأحجار الزركون الفاخرة',
    slug: { current: 'luxury-zircon-gold-necklace' },
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 18500,
    oldPrice: 24000,
    discountPercentage: 23,
    shortDescription: 'عقد مطلي بالذهب عيار 18 بتصميم كلاسيكي ساحر يناسب أرقى المناسبات.',
    description: 'قطعة فنية استثنائية من مجوهرات ليفورا. عقد مصنوع بعناية فائقة من الفولاذ المقاوم للصدأ ومطلي بطبقات غنية من الذهب عيار 18 مع أحجار الزركون النقية عاكسة للضوء. لا يبهت لونه ومقاوم للماء والحساسية.',
    category: {
      _ref: 'cat-accessories',
      _type: 'reference',
      name: 'الإكسسوارات',
      slug: 'accessories',
    },
    colors: [
      { name: 'ذهب أصفر', hex: '#C8A96B' },
      { name: 'ذهب وردي', hex: '#E0A899' },
      { name: 'فضة بلاتين', hex: '#E5E5E5' },
    ],
    sizes: ['45 سم (قابل للتعديل)', '50 سم'],
    sku: 'LIV-ACC-001',
    displayStockCount: 4,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isOnSale: true,
    rating: 5,
    reviewsCount: 28,
    createdAt: '2026-02-15T10:00:00Z',
    details: {
      material: 'فولاذ مقاوم للصدأ مطلي بذهب عيار 18 قيراط',
      origin: 'تصميم إيطالي حصري',
      careInstructions: 'يحفظ في علبة ليفورا الفاخرة بعيداً عن الكحول المباشر',
      warranty: 'ضمان ثبات اللون لمدة عام كامل',
    },
  },
  {
    _id: 'prod-2',
    name: 'مجموعة أحمر الشفاه المخملي "ريد فيلفيت كولكشن"',
    slug: { current: 'velvet-matte-lipstick-set' },
    mainImage: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 12500,
    oldPrice: 16000,
    discountPercentage: 22,
    shortDescription: 'طقم يحتوي على 4 درجات مخملية ثابتة تدوم طوال اليوم دون أن تسبب جفاف الشفاه.',
    description: 'تألقي بجاذبية الشفاه الممتلئة مع تشكيلة ليفورا المخملية. تركيبة نباتية معززة بزبدة الشيا وفيتامين E لتغذية وترطيب الشفاه مع لون صبغي مركز وثبات فائق يدوم حتى 16 ساعة.',
    category: {
      _ref: 'cat-makeup',
      _type: 'reference',
      name: 'المكياج',
      slug: 'makeup',
    },
    colors: [
      { name: 'روز نود', hex: '#C27D7D' },
      { name: 'توت غامق', hex: '#7A1C30' },
      { name: 'كلاسيك ريد', hex: '#B31B1B' },
      { name: 'موكا دافئ', hex: '#8B5A2B' },
    ],
    sku: 'LIV-MKP-042',
    displayStockCount: 7,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 45,
    createdAt: '2026-02-18T12:30:00Z',
    details: {
      material: 'مستخلصات طبيعية 100% مع فيتامين E',
      origin: 'فرنسا',
      careInstructions: 'يحفظ في مكان جاف وبارد',
      warranty: 'منتج أصلي ومضمون',
    },
  },
  {
    _id: 'prod-3',
    name: 'سيروم حمض الهيالورونيك وفيتامين C المركز للنضارة الفورية',
    slug: { current: 'hyaluronic-vitamin-c-glow-serum' },
    mainImage: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1608248597359-0a6e0df36545?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 14000,
    oldPrice: 19000,
    discountPercentage: 26,
    shortDescription: 'تركيبة فائقة النقاء تمنح بشرتك نضارة زجاجية وترطيباً عميقاً يحارب التجاعيد المبكرة.',
    description: 'أعيدي الحيوية والشباب لبشرتك مع سيروم ليفورا المركز. يحتوي على تركيز 5% من فيتامين C النقي و 2% حمض الهيالورونيك متعدد الأوزان الجزيئية لتوحيد لون البشرة وتقليل التصبغات ومقاومة علامات الإجهاد.',
    category: {
      _ref: 'cat-skincare',
      _type: 'reference',
      name: 'منتجات العناية',
      slug: 'skincare',
    },
    sizes: ['30 مل', '50 مل'],
    sku: 'LIV-SKN-105',
    displayStockCount: 5,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isOnSale: true,
    rating: 5,
    reviewsCount: 39,
    createdAt: '2026-02-22T14:15:00Z',
    details: {
      material: 'خالٍ من العطور والبارابين والكحول',
      origin: 'كوريا الجنوبية',
      careInstructions: 'يستخدم صباحاً ومساءً على بشرة نظيفة قبل المرطب',
      warranty: 'مختبر سريرياً ومطابق للمواصفات العالمية',
    },
  },
  {
    _id: 'prod-4',
    name: 'حقيبة ليفورا الجلدية الفاخرة مع قفل ذهبي مميز',
    slug: { current: 'livora-signature-luxury-leather-bag' },
    mainImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 32000,
    oldPrice: 42000,
    discountPercentage: 24,
    shortDescription: 'حقيبة كتف ويد بتصميم أيقوني من الجلد النباتي الإيطالي عالي الجودة مع حزام ذهبي قابل للتعديل.',
    description: 'رمز الفخامة والعملية في آن واحد. حقيبة ليفورا الأيقونية بحجم مثالي يتسع لجميع مقتنياتك اليومية ومكياجك وهاتفك، مع بطانة حريرية داخلية وتقسيمات منظمة وإكسسوارات معدنية مطلية بالذهب مقاومة للخدش.',
    category: {
      _ref: 'cat-bags',
      _type: 'reference',
      name: 'الحقائب',
      slug: 'bags',
    },
    colors: [
      { name: 'عاجي دافئ (Ivory)', hex: '#F6F0E8' },
      { name: 'أسود أونيكس (Onyx)', hex: '#171717' },
      { name: 'كراميل ناعم (Caramel)', hex: '#A66E38' },
      { name: 'برغندي ملكي', hex: '#5E1914' },
    ],
    sizes: ['المقاس الكلاسيكي: 24 × 16 × 8 سم'],
    sku: 'LIV-BAG-088',
    displayStockCount: 3,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isOnSale: true,
    rating: 5,
    reviewsCount: 19,
    createdAt: '2026-02-25T09:00:00Z',
    details: {
      material: 'جلد نباتي إيطالي فاخر من الدرجة الأولى',
      origin: 'تصميم فلورنسي حصري',
      careInstructions: 'تنظف بقطعة قماش ناعمة وجافة وتخزن في حقيبة الغبار المرفقة',
      warranty: 'ضمان عام كامل على السحابات والجلود',
    },
  },
  {
    _id: 'prod-5',
    name: 'طقم فراشي المكياج المخملية من الكشمير (12 قطعة مع حقيبة)',
    slug: { current: 'luxury-cashmere-brush-set-12pcs' },
    mainImage: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 15500,
    oldPrice: 21000,
    discountPercentage: 26,
    shortDescription: 'فراشي تجميل احترافية بشعيرات ناعمة كالحرير ومقابض أنيقة بلمسات ذهبية.',
    description: 'تطبيق مكياج ناعم ومثالي كالمحترفين. يضم الطقم جميع الفراشي الأساسية للوجه والعيون والكونتور والدمج مع حقيبة ليفورا الفاخرة المدمجة المقاومة للماء والأتربة.',
    category: {
      _ref: 'cat-beauty-tools',
      _type: 'reference',
      name: 'أدوات التجميل',
      slug: 'beauty-tools',
    },
    colors: [
      { name: 'ذهبي عاجي', hex: '#C8A96B' },
      { name: 'وردي شيفون', hex: '#EBB4B4' },
    ],
    sku: 'LIV-TLS-019',
    displayStockCount: 6,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isOnSale: true,
    rating: 4.8,
    reviewsCount: 31,
    createdAt: '2026-02-10T16:20:00Z',
  },
  {
    _id: 'prod-6',
    name: 'طوق شعر لؤلؤي مرصع بالكريستال اللامع',
    slug: { current: 'pearl-crystal-luxury-headband' },
    mainImage: 'https://images.unsplash.com/photo-1535295972055-1c762f4483e5?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 6500,
    oldPrice: 9000,
    discountPercentage: 28,
    shortDescription: 'إكسسوار شعر ملكي مزين بلآلئ المياه العذبة وكريستالات براقة تميز مناسباتك الخاصة.',
    description: 'تألقي بإطلالة أميرة مع طوق الشعر الاستثنائي من ليفورا. مبطن بقماش حريري فائق النعومة لمنع الضغط على الرأس ومثبت بحرفية يدوية متناهية.',
    category: {
      _ref: 'cat-hair-accessories',
      _type: 'reference',
      name: 'إكسسوارات الشعر',
      slug: 'hair-accessories',
    },
    colors: [
      { name: 'لؤلؤ أبيض ملكي', hex: '#FFFFFF' },
      { name: 'شمبانيا جولد', hex: '#DEC593' },
    ],
    sku: 'LIV-HAR-077',
    displayStockCount: 9,
    isFeatured: false,
    isBestSeller: true,
    isNew: true,
    isOnSale: true,
    rating: 5,
    reviewsCount: 22,
    createdAt: '2026-02-24T18:00:00Z',
  },
  {
    _id: 'prod-7',
    name: 'عطر مسك الفانيليا والياسمين الليلي "LIVORA NOIR"',
    slug: { current: 'livora-noir-luxury-parfum' },
    mainImage: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 26000,
    oldPrice: 34000,
    discountPercentage: 24,
    shortDescription: 'عطر نسائي شرقي غربي ساحر بمزيج المسك الأبيض وخشب الصندل ونفحات الفانيليا الملكية.',
    description: 'رائحة تأسر الحواس وتبقى عالقة في الذاكرة. عطر أو دو بارفيوم بتركيز 25% من الزيوت العطرية النقية لثبات يستمر لأكثر من 24 ساعة وفواحان يخطف الأنفاس.',
    category: {
      _ref: 'cat-beauty-care',
      _type: 'reference',
      name: 'منتجات الجمال',
      slug: 'beauty-products',
    },
    sizes: ['100 مل'],
    sku: 'LIV-PRF-009',
    displayStockCount: 4,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isOnSale: false,
    rating: 5,
    reviewsCount: 54,
    createdAt: '2026-02-26T11:00:00Z',
    details: {
      material: 'زيوت فرنسية نقية مع المسك الأبيض',
      origin: 'غراس - فرنسا',
      careInstructions: 'يرش على نقاط النبض والملابس',
      warranty: 'ثبات وفواحان مضمون',
    },
  },
  {
    _id: 'prod-8',
    name: 'سوار ذهبي متصل مع خاتم بنمط الأرابيسك العصري',
    slug: { current: 'modern-arabesque-gold-bracelet-ring' },
    mainImage: 'https://images.unsplash.com/photo-1611591475155-42e9fba5ce55?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 16000,
    oldPrice: 20000,
    discountPercentage: 20,
    shortDescription: 'سوار وخاتم مدمج بتصميم شرقي حديث مطلي بذهب عيار 18 قيراط مع نقوش هندسية دقيقة.',
    description: 'قطعة لافتة للأنظار مستوحاة من التراث العربي الأندلسي بلمسة عصرية فاخرة. مريحة في الارتداء وقابلة لتعديل المقاس لتناسب جميع معاصم اليدين.',
    category: {
      _ref: 'cat-accessories',
      _type: 'reference',
      name: 'الإكسسوارات',
      slug: 'accessories',
    },
    colors: [
      { name: 'ذهب عيار 18', hex: '#C8A96B' },
      { name: 'ذهب أبيض مطلي', hex: '#E5E5E5' },
    ],
    sku: 'LIV-ACC-018',
    displayStockCount: 5,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 16,
    createdAt: '2026-02-27T15:45:00Z',
  },
  {
    _id: 'prod-9',
    name: 'رول تدليك الوجه بحجر اليشم الأخضر وحجر الجواشا الطبيعي',
    slug: { current: 'natural-jade-roller-guasha-set' },
    mainImage: 'https://images.unsplash.com/photo-1608248597359-0a6e0df36545?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 8500,
    oldPrice: 11000,
    discountPercentage: 22,
    shortDescription: 'أداة عناية صينية تقليدية لشد البشرة وتنشيط الدورة الدموية والتخلص من انتفاخ تحت العينين.',
    description: 'استرخي واستمتعي بجلسة سبا منزلية يومية. رول وحجر جواشا مصنوعان من حجر اليشم الطبيعي 100%، يساعدان على امتصاص السيرومات والزيوت بعمق ونحت الفك والخدين.',
    category: {
      _ref: 'cat-beauty-tools',
      _type: 'reference',
      name: 'أدوات التجميل',
      slug: 'beauty-tools',
    },
    sku: 'LIV-TLS-044',
    displayStockCount: 8,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isOnSale: true,
    rating: 4.8,
    reviewsCount: 27,
    createdAt: '2026-02-14T08:00:00Z',
  },
  {
    _id: 'prod-10',
    name: 'أقراط اللؤلؤ المتدلية بطلاء الذهب والزركون',
    slug: { current: 'drop-pearl-gold-zircon-earrings' },
    mainImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
    ],
    price: 9500,
    oldPrice: 13000,
    discountPercentage: 27,
    shortDescription: 'أقراط ناعمة وأنيقة تضيف لمسة من النقاء والأنوثة لأي إطلالة يومية أو مسائية.',
    description: 'أقراط ليفورا المتدلية مصنوعة من لؤلؤ باروكي صناعي نخب أول مع قواعد ذهبية مضادة للحساسية ومريحة للأذن طوال اليوم.',
    category: {
      _ref: 'cat-accessories',
      _type: 'reference',
      name: 'الإكسسوارات',
      slug: 'accessories',
    },
    sku: 'LIV-ACC-033',
    displayStockCount: 7,
    isFeatured: false,
    isBestSeller: true,
    isNew: true,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 21,
    createdAt: '2026-02-28T09:10:00Z',
  },
];

export const defaultHeroSlides: HeroSlide[] = [
  {
    _id: 'hero-1',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1600&auto=format&fit=crop',
    title: 'أنوثة خالدة وفخامة تليق بك',
    subtitle: 'تشكيلة ليفورا الجديدة لعام 2026',
    description: 'اكتشفي أرقى الإكسسوارات، المكياج الأصلي، ومنتجات العناية المختارة بعناية للمرأة اليمنية الأنيقة مع خدمة توصيل لجميع المحافظات.',
    ctaText: 'اكتشفي التشكيلة الآن',
    ctaLink: '/products',
    badge: 'تخفيضات موسمية حصرية',
    active: true,
    order: 1,
  },
  {
    _id: 'hero-2',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1600&auto=format&fit=crop',
    title: 'إشراقة ساحرة ولمسات مكياج ناعمة',
    subtitle: 'أحدث درجات الروج والباليتات الأصلية',
    description: 'ألوان تدوم طوال اليوم وتركيبات غنية تبرز جمالك الطبيعي وتمنحك الثقة في كل خطوة.',
    ctaText: 'تسوقي المكياج',
    ctaLink: '/products?category=makeup',
    badge: 'الأكثر مبيعاً',
    active: true,
    order: 2,
  },
  {
    _id: 'hero-3',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1600&auto=format&fit=crop',
    title: 'بريق الذهب وأناقة المجوهرات',
    subtitle: 'إكسسوارات مطلية بذهب عيار 18',
    description: 'تصاميم استثنائية مقاومة للماء والبهتان لتبقى ذكراك خالدة ومظهرك متألقاً دائماً.',
    ctaText: 'تسوقي الإكسسوارات',
    ctaLink: '/products?category=accessories',
    badge: 'تصاميم حصرية',
    active: true,
    order: 3,
  },
];

export const defaultTestimonials: Testimonial[] = [
  {
    _id: 'test-1',
    name: 'سارة الكبسي',
    city: 'صنعاء',
    text: 'ما شاء الله التغليف جداً راقي وفخم، والعقد الذهبي طلع أجمل بكثير من الصور على الطبيعة ولمعته تجنن! والتوصيل في صنعاء كان سريع جداً.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    active: true,
    order: 1,
    date: 'منذ أسبوع',
  },
  {
    _id: 'test-2',
    name: 'فاطمة باعباد',
    city: 'عدن',
    text: 'طلبت روج ريد فيلفيت وسيروم النضارة، المنتجات أصلية 100% وجودتها عالية جداً. تعامل فريق الواتساب محترم وراقي وسريعين بالرد.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
    active: true,
    order: 2,
    date: 'منذ أسبوعين',
  },
  {
    _id: 'test-3',
    name: 'مها الصبري',
    city: 'تعز',
    text: 'حقيبة اليد الأيقونية خياطتها وتفاصيلها الجلدية تضاهي الماركات العالمية، حجمها ممتاز جداً ومناسبة للدوام والمناسبات. شكراً ليفورا!',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    active: true,
    order: 3,
    date: 'منذ 3 أسابيع',
  },
  {
    _id: 'test-4',
    name: 'خلود النعيمي',
    city: 'المكلا',
    text: 'فراشي المكياج ناعمة جداً وما تتساقط أبداً، ووصلتني للمكلا بحالة ممتازة في بوكس ليفورا الفاخر. متجري المفضل بلا منازع.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    active: true,
    order: 4,
    date: 'منذ شهر',
  },
];

export const defaultSiteSettings: SiteSettings = {
  storeName: 'ليفورا | LIVORA',
  storeNameEn: 'LIVORA Luxury Store',
  tagline: 'عالمكِ الخاص للجمال والأناقة والفخامة النسائية',
  logo: '/logo.svg',
  whatsappNumber: '967737462144',
  instagram: 'https://instagram.com/livora.ye',
  tiktok: 'https://tiktok.com/@livora.ye',
  snapchat: 'https://snapchat.com/add/livora.ye',
  storeDescription: 'متجر ليفورا النسائي الفاخر - وجهتكِ الأولى في اليمن لأرقى الإكسسوارات والمكياج ومنتجات العناية بالبشرة والجمال.',
  contactInformation: {
    address: 'الجمهورية اليمنية - التوصيل متوفر لجميع المحافظات (صنعاء، عدن، تعز، المكلا، إب وكافة المناطق)',
    phone: '+967 737 462 144',
    email: 'info@livora-store.com',
    workingHours: 'يومياً من الساعة 9:00 صباحاً حتى 11:00 مساءً',
  },
  footerText: 'جميع الحقوق محفوظة لمتجر ليفورا © 2026 | صُمم بشغف لجمالكِ الفاخر',
  defaultSEO: {
    metaTitle: 'LIVORA | ليفورا - متجر نسائي فاخر',
    metaDescription: 'تسوقي أرقى الإكسسوارات، المكياج ومنتجات العناية في اليمن عبر متجر ليفورا مع طلب مباشر عبر الواتساب.',
  },
  currency: {
    symbol: 'ر.ي',
    code: 'YER',
    exchangeRateToUSD: 530,
  },
};
